# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BOG_simmat_cpp <- function(d2g, totalGeneNum, GeneNumList) {
    .Call('dSimer_BOG_simmat_cpp', PACKAGE = 'dSimer', d2g, totalGeneNum, GeneNumList)
}

BOG_normat_cpp <- function(D1, D2, simmat, matnameloc, maxsim, IC) {
    .Call('dSimer_BOG_normat_cpp', PACKAGE = 'dSimer', D1, D2, simmat, matnameloc, maxsim, IC)
}

go2g_full <- function(go2g, go_offsp) {
    .Call('dSimer_go2g_full', PACKAGE = 'dSimer', go2g, go_offsp)
}

TDistanceMat_cpp <- function(SDistanceMat, A, b) {
    .Call('dSimer_TDistanceMat_cpp', PACKAGE = 'dSimer', SDistanceMat, A, b)
}

ICod_onepair_cpp <- function(SDis, TDis, C) {
    .Call('dSimer_ICod_onepair_cpp', PACKAGE = 'dSimer', SDis, TDis, C)
}

PSB_termsim_cpp <- function(go_jaccardindex, IC) {
    .Call('dSimer_PSB_termsim_cpp', PACKAGE = 'dSimer', go_jaccardindex, IC)
}

Sun_topology_cpp <- function(D1, D2, d2g, graphlet_signature, weight) {
    .Call('dSimer_Sun_topology_cpp', PACKAGE = 'dSimer', D1, D2, d2g, graphlet_signature, weight)
}

